<?php

namespace ETECH\SSOTestBundle\Entity;

/**
 * SSO_UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SSO_UserRepository extends \Doctrine\ORM\EntityRepository
{
}
