etechsso_test:
    resource: "@ETECHSSOTestBundle/Resources/config/routing.yml"
    prefix:   /
#REST 
rest : 
    type : rest 
    resource : "routing_rest.yml"
    prefix : /
  
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
